name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          path: src/backend
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-github-pull-request: true
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      tag_name: ${{ steps.release.outputs.tag_name }}
  tag-major-minor:
    runs-on: ubuntu-latest
    needs: [release-please-release]
    if: ${{ needs.release-please-release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v5
      - name: Tag major and minor versions
        run: |
          # Get the latest tag and major/minor versions from the previous step
          LATEST_TAG="${{ needs.release-please-release.outputs.tag_name }}"
          MAJOR="v${{ needs.release-please-release.outputs.major }}"
          MINOR="v${{ needs.release-please-release.outputs.major }}.${{ needs.release-please-release.outputs.minor }}"
          
          # Configure git for tagging
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          echo "Updating tags: Major=${MAJOR}, Minor=${MINOR} to point to ${LATEST_TAG}"

          # Delete existing tags if they exist
          git tag -d "${MAJOR}" || true
          git tag -d "${MINOR}" || true
          git push origin :"${MAJOR}" || true
          git push origin :"${MINOR}" || true
          
          # Create new tags pointing to the latest release tag
          git tag -a "${MAJOR}" -m "Release ${MAJOR}" "${LATEST_TAG}"
          git tag -a "${MINOR}" -m "Release ${MINOR}" "${LATEST_TAG}"

          # Push new tags
          git push origin "${MAJOR}"
          git push origin "${MINOR}"
  release-please-pull-request:
    runs-on: ubuntu-latest
    needs: [release-please-release]
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          path: src/backend
          release-type: python
          skip-github-release: true
          token: ${{ secrets.GITHUB_TOKEN }}